### ISSUE TITLE
Maven compilation under Windows

### ISSUE THREAD

**Issue by FilipGh** [Kortforsyningen/PROJ-JNI#30]
When running the maven compilation process under *Windows*, I encountered a few errors.

* 1st error
<pre>Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project proj:
Fatal error compiling: invalid flag: --release
</pre>
Need to suppress the following line in *POM.XML* file: `<release>8</release>`

* 2nd error
<pre>
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project proj:
Fatal error compiling: invalid flag: --doclint-format
...
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project proj:
Fatal error compiling: invalid flag: html5
</pre>
Need to suppress the following line  in *POM.XML* file: `<arg>--doclint-format</arg> <arg>html5</arg>`

* 3rd error
<pre>
UnitType.java:[134,59] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
NativeResource.java:[205,67] lambda expressions are not supported in -source 1.6
  (use -source 8 or higher to enable lambda expressions)
</pre>
I added the following lines in *POM.XML* file:
`<source>1.8</source>`
`<target>1.8</target>`

Attached is the git diff file.
[pom.xml.zip](https://github.com/Kortforsyningen/PROJ-JNI/files/4018760/pom.xml.zip)

**Comment by desruisseaux** [comment]
Actually in its current configuration, PROJ-JNI requires Java 9 or later for building even if the output JAR file targets Java 8. The reason is that `<source>` and `<target>` options are not reliable ways to target Java 8 platform if the project is built with a more recent Java version — we also need to set the `<bootclasspath>` option, which is a quite difficult task (it requires a path to a Java 8 installation). Java 9 provides a much easier option — `<release>`  — which does all the work of `<source>`, `<target>` and `<bootclasspath>` together.

Is there a need to build PROJ-JNI with Java 8 (as opposed to only _execute_ PROJ-JNI with Java 8)? If yes then the proposed patch could be applied. If compiling with Java 9 or later is acceptable, then the current configuration may actually be more robust.

**Comment by FilipGh** [comment]
That might be OK to compile with Java 9, as long as the byte code is "Java 8" compatible. If it is more robust and reliable as it is, it is better like that. You are the guy who knows :-)

**Comment by desruisseaux** [comment]
Yes with the legacy `--source` and `--target` options, we are guaranteed to have Java 8 compatible code only if building with exactly the Java 8 version, or building with a more recent Java version together with the `--bothclasspath` options pointing to a Java 8 installation. Since Java 9, the `--release 1.8` option produces Java 8 compatible code in all cases without the need to have a Java 8 around. But indeed current configuration creates the paradoxical situation of requiring Java 9+ for building Java 8 compatible code…

I'm closing this issue, but please feel free to reopen it if there is a need to make the project buildable with Java 8.
